spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quarks_commerce
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379

server:
  port: 8080

logging:
  level:
    org.springframework: INFO 